### ISSUE TITLE
Beep sound doesn't play & some performance metrics

### ISSUE THREAD

**Issue by C43H66N12O12S2** [KeinNiemand/LargePageInjectorMods#1]
Whether launched from Injector.exe or the Paradox Launcher, the beep sound doesn't play. Executing Injector.exe from the Terminal claims the injection was successful.

With a 7950X3D and 96GB RAM, on a early 1000 galaxy size, 30 empire modded save, the original game processed 10K turns in 96 secs inside observer mode. After injecting mimalloc with eager commit and 16GiB hugepages, that dropped down to 91 secs.

I'd expect that gap to widen as the save progresses, though it's still lower than I expected given my previous experiences doing this (on Linux, at least). That was with a different CPU though, so maybe the 7950X3D is not as sensitive, or the injection fails at some step (given the beep sound does not play).

**Comment by KeinNiemand** [comment]
There no error checking or anything involved with the Beep, it's basically just there to know that the dll actually got injected and did something, it calls the Win32 Beep function right before launching the game regardless if anything failed or not (unless it crashes but in that case the game woudn't open). No idea why you don't get the beep but it might be muted or something.

As for why the performance gain is so small compared to what it was for you on linux I don't really know I never tried it on linux, did you check if you where actually using large pages (using RamMap https://learn.microsoft.com/de-de/sysinternals/downloads/rammap that program can show you if any large pages are in use, did you reboot after setting the lock pages in memory permission and the environment variables, it dosn't apply without a reboot.

It could also be worse on windows, since windows dosn't support 1GB pages, it only supports 2MB Large Pages. Also MSVC is as far as I know a somewhat slower compiler then gcc or clang or whatever mimalloc get's compiled with for linux so maybe that also affects things. I don't really know. Or maybe it's for any of the other reasons that 


The performance gains reported by diffrent people have varied wildley, somone on the StellerStellaris discord got 10-15% with large pages, but he also reported that his friend with weaker hardware got 80% improvement. 
There's a got chance that the performance improments smaller with better hardware.
Don't really have enough data to say exactly how the improvment scales with hardware and game year (probably more of an improvment late game), 
I used a mo end game 2450 save for the 22.5% number I got and a 2500 vanilla save for the original 200% (there was probably something wrong witht that measturement).

**Comment by C43H66N12O12S2** [comment]
![a](https://github.com/KeinNiemand/LargePageInjectorMods/assets/36072735/9cfeab07-3600-480a-919c-8a8c47df5b81)
In my experience, allocator replacements help more and more as the working set spills out of cache, so it's somewhat expected V-Cache parts like mine with huge caches will benefit less, and the save I used for measurement was really early (10 years after start IIRC).

All this to say, I opened this issue to make sure there wasn't a known bug affecting my results, and if there isn't, to provide another set of results.

Notes:
Eager commit had a performance improvement in all cases (though marginal.)
Large pages ran worse than allocating hugepages, though this might change for people with limited RAM (<=16GB)
Windows version of Stellaris definitely runs slower than Linux pound-for-pound.

Thank you for the awesome project.
